### PR TITLE
adding sphinx-gallery example

### PR DESCRIPTION
**Pull request by choldgraf**
This adds a quick example and renders it with sphinx gallery. It generates this gallery currently:

image

Which is a gallery-ified version of the jupyter notebook that's in there. It also removes the `pngmath` extension as this was deprecated, and `mathjax` is being loaded anyway.

LMK if you'd like to see another example in there. If so, can you give me a script that uses shablona to plot something pretty and I can add it in? @arokem

### CODE REVIEW

**Comment by arokem** [comment]
This is great! 

We'll still need to add some explanation about how this all works to the README as well.

Is there any reason you made the PR against my fork (rather than https://github.com/uwescience/shablona)?

**Comment by choldgraf** [comment]
ah oops - no I just missed that I'll open a PR there and will add an explanation etc. Can you give me one python script that generates another plot using this package first? Then I can incorporate at least two which is better-suited for the gallery layout.

**Comment by choldgraf** [comment]
hey - I opened this up as a PR on the main repo, just FYI. I'll close this now.

**Comment by arokem** [comment]
Yes - I saw that. Thank you!

**Pull request closed without merging**
